// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function GetUSBDevices() {
  return window['go']['main']['App']['GetUSBDevices']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDependencies() {
  return window['go']['main']['App']['InstallDependencies']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Off() {
  return window['go']['main']['App']['Off']();
}

export function SaveColorSetting(arg1) {
  return window['go']['main']['App']['SaveColorSetting'](arg1);
}

export function SetColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetColor'](arg1, arg2, arg3);
}
