// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies():Promise<Record<string, any>>;

export function Connect():Promise<void>;

export function GetUSBDevices():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallDependencies():Promise<void>;

export function LoadSettings():Promise<Record<string, any>>;

export function Off():Promise<void>;

export function SaveColorSetting(arg1:string):Promise<void>;

export function SetColor(arg1:number,arg2:number,arg3:number):Promise<void>;
